// grab our gulp packages
var gulp  = require('gulp'),
    gutil = require('gulp-util');

/*// create a default task and just log a message
gulp.task('default', function() {
  return gutil.log('Gulp is running!')
});*/


//Gulp&Karma Integration.----------------------
var Server = require('karma').Server;


// Run test once and exit 
gulp.task('test', function (done) {
  new Server({
    configFile: __dirname + '/Karma.conf.js',
    singleRun: true
  }, done).start();
});


// Watch for file changes and re-run tests on each change
gulp.task('tdd', function (done) {
  new Server({
    configFile: __dirname + '/Karma.conf.js'
  }, done).start();
});

gulp.task('default', ['tdd']);
//Gulp&Karma Integration.----------------------

//Watching file changes task---------------------------------------------------
//> gulp autotest
gulp.task('autotest', function() {
  console.log("autotest task is running..");
  return gulp.watch(['test/*.js', 'testA/*.js', 'public/*.*', 'app/*.js'], ['test']);  //Whenever listed files changes.. Run "test" task...
});



//Concatenate & Minify Javascript with Gulp, Improve Site Performance--------------------------
//> gulp concatUglify
var concat = require('gulp-concat');  
var rename = require('gulp-rename');  
var uglify = require('gulp-uglify');

//script paths
var jsFiles = 'public/js/*.js',   //'assets/scripts/**/*.js',  
    jsDest = 'dist/scripts';

gulp.task('concatUglify', function() {  
    return gulp.src(jsFiles)
        .pipe(concat('scripts.js'))   //new scripts.js file will be created...
        .pipe(gulp.dest(jsDest))
        .pipe(rename('scripts.min.js')) //renames script.js file which was generated by concatinating...
        .pipe(uglify())
        .pipe(gulp.dest(jsDest));
});

//AND gulp.task('default', ['concatUglify']);


//SCSS to CSS conversion...